### PR TITLE
Extending sampled but exception when using a command binding

### PR DESCRIPTION
**Pull request by escamoteur**
Added new Page to the sample project and added the Projects for the RxUI version. They stay at the moment unloaded because they do not compile.

Somehow the sample crashes as soon as I try to bind a command. Perhaps I'm just stupid today, don't know

I had to change the target profile before I could build te Sample project

### CODE REVIEW

**Comment by daniel-luberda** [comment]
That's great :)  good work

**Comment by escamoteur** [comment]
are you later on Slack?

**Comment by escamoteur** [comment]
Would you do the merge?

**Comment by daniel-luberda** [comment]
Yes, I'll try to merge it now :)

**Comment by escamoteur** [comment]
Any problems with the merge?

**Pull request merged**
